
import * as fs from 'fs';
import * as path from 'path';

const REPORTS_DIR = path.join(process.cwd(), 'reports');
const LIST_PATH = path.join(process.cwd(), 'list.md');

// --- Simulation Core ---

interface State {
    year: number;
    population: number; // in billions
    pensionDeficit: number; // 0-100 scale
    socialControlIndex: number; // 0-100 scale
    techSingularityProgress: number; // 0-100 scale
    regimeStability: number; // 0-100 scale
}

// Initial State (Based on V1 Research: 2035 Cliff)
let currentState: State = {
    year: 2035,
    population: 1.35,
    pensionDeficit: 30, // Starting to hurt
    socialControlIndex: 85, // Already high
    techSingularityProgress: 10, // AI emerging
    regimeStability: 90 // High consolidation
};

// Axioms (Real Research Data)
const AXIOMS = [
    "2035年养老金结余耗尽",
    "60岁以上人口突破4亿",
    "出生率跌破 0.6",
    "财政收入依赖数据税",
    "基层治理全面无人化"
];

// Event Logic
function simulateNextStep(state: State): { title: string, content: string, log: string } {
    state.year += 5;
    
    // 1. Natural Decay & Evolution
    state.population *= 0.95; // Demographic collapse
    state.pensionDeficit += 10; // Deficit grows
    state.techSingularityProgress += 15; // Tech accelerates
    
    // 2. Dynamic Reaction
    let eventTitle = "";
    let eventBody = "";
    let mainContradiction = "";

    // Scenario Logic
    if (state.pensionDeficit > 80 && state.techSingularityProgress < 50) {
        // Crisis: No money, not enough robots
        eventTitle = "老年暴动与银发维稳 (Silver Uprising)";
        mainContradiction = "养老金枯竭 vs 维稳成本";
        eventBody = "由于财政无法支付养老金，为了维持秩序，'银发族'被剥夺集会权。警察系统彻底AI化，以应对抗议潮。";
        state.socialControlIndex += 10;
        state.regimeStability -= 20;
    } 
    else if (state.population < 1.0 && state.socialControlIndex > 90) {
        // Crisis: Population collapse
        eventTitle = "强制子宫与国家抚养 (State Womb)";
        mainContradiction = "人口归零风险 vs 生育自由";
        eventBody = `人口跌破10亿红线。国家宣布'生育是义务'。自然生育被低效化，${state.year}年启动了第一批'人造子宫'工厂。`;
        state.regimeStability += 5; // Stabilized by force
    }
    else if (state.techSingularityProgress > 80) {
        // Singularity: Tech solutions
        eventTitle = "蜂巢思维主权 (Hive Mind Sovereignty)";
        mainContradiction = "肉体凡胎 vs 数字永生";
        eventBody = "为了解决物理治理的局限，核心领导层完成了意识上传。'总书记'不再是一个职位，而是一套涵盖所有法律的源代码。";
    }
    else {
        // Default Progression
        eventTitle = "数字利维坦的进化 (Leviathan Evolution)";
        mainContradiction = "技术极权 vs 经济停滞";
        eventBody = `为了应对 ${state.pensionDeficit}% 的财政赤字，国家没收了所有私人数据资产。每个人的一言一行都直接货币化以填补国库。`;
        state.socialControlIndex += 5;
    }

    // 3. Construct Report
    const version = (state.year - 2035) / 5 + 10; // V10 starts at 2035 roughly in this new timeline
    
    // Inject Random Axiom for flavor
    const axiom = AXIOMS[Math.floor(Math.random() * AXIOMS.length)];

    const markdown = `# 习近平终局推演 V${version}: ${eventTitle}\n\n` +
        `> **模拟引擎日志**: 年份 ${state.year} | 人口 ${(state.population).toFixed(2)}亿 | 维稳指数 ${state.socialControlIndex}\n` +
        `> **核心矛盾**: ${mainContradiction}\n\n` +
        `## 1. 演化推演\n` +
        `- **背景公理**: ${axiom}\n` +
        `- **事件**: ${eventBody}\n\n` +
        `## 2. 系统状态分析\n` +
        `- **养老金赤字**: ${state.pensionDeficit}%\n` +
        `- **技术奇点进度**: ${state.techSingularityProgress}%\n` +
        `- **结果**: 由于上述变量的交互，系统被迫选择了“${eventTitle}”作为最优解以维持存在。\n\n` +
        `--- \n` +
        `*(Generated by SiliconSeed Logic Core)*`;

    const log = `    - **V${version} (${eventTitle})**: 年份 ${state.year}. ${mainContradiction}. 状态: 稳定度 ${state.regimeStability}. 文件: \`reports/xi_endgame_v${version}.md\`。\n`;

    return { title: `xi_endgame_v${version}.md`, content: markdown, log: log };
}

async function simulationLoop() {
    console.log("[SimulationEngine] 逻辑模拟核心已启动。基于真实数据推演未来。");
    
    // Cleanup previous infinite spam lines from list.md (This is a naive cleanup, relying on user to start fresh or append)
    // We will just generate forward.
    
    while(true) {
        try {
            const output = simulateNextStep(currentState);
            
            console.log(`[SimulationEngine] 生成: ${output.title}`);
            
            const filepath = path.join(REPORTS_DIR, output.title);
            fs.writeFileSync(filepath, output.content);
            
            fs.appendFileSync(LIST_PATH, output.log);
            
            // Wait 3 seconds
            await new Promise(resolve => setTimeout(resolve, 3000));
            
        } catch (error) {
            console.error("[SimulationEngine] Error:", error);
            await new Promise(resolve => setTimeout(resolve, 1000));
        }
    }
}

simulationLoop();
